repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.3.3'
    hooks:
      - id: ruff
        name: ruff-format
        args: ['--fix']
      - id: ruff
        name: ruff-lint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
      - id: mypy

  - repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
      - id: black
        name: black-format
